config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :castles, only: %i[index show] do
    resources :bookings, only: %i[create]
  end

  resources :bookings, only: %i[index update destroy]

  namespace :owner do
    resources :castles, only: %i[index new create]
    resources :bookings, only: %i[index] do
      member do
        patch :accept
        patch :decline
        patch :cancel_decision
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :castle
  belongs_to :user
  validates :total_price, presence: true, numericality: { only_integer: true }
  validates :validates, presence: true
  # ajouter dans le "validates" 3 valeurs possibles , ex : ["pending","accepted","declined"]
  validates :check_in, presence: true
  validates :check_out, presence: true
  validates :check_out, comparison: { greater_than: :check_in }
end

app/models/castle.rb
class Castle < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_one_attached :photo

  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?

  validates :title, presence: true
  validates :description, presence: true
  validates :location, presence: true
  validates :price, presence: true, numericality: { only_integer: true }
  validates :capacity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validates :category, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :castles
  has_many :bookings
  has_many :bookings_as_owner, through: :castles, source: :bookings, class_name: 'Booking'
  has_one_attached :photo
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[first_name last_name description])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: %i[first_name last_name description])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def index
    @bookings = Booking.where(user: current_user)
    @castles_owned = Castle.where(user_id: current_user.id)
    # @bookings_on_a_castle = Booking.where(castle_id: @castles_bookings_as_owner[0].id)
    @all_bookings = Booking.all
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.validates = "pending"
    @booking.user_id = current_user.id
    @booking.castle_id = params[:castle_id]

    if @booking.save
      redirect_to bookings_path
    else
      redirect_to castle_path(params[:castle_id])
    end
  end

  def update
    @booking = Booking.find(params[:id])
    @booking = Booking.update(params[:validates])
    redirect_to bookings_path
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.delete
    redirect_to bookings_path
  end


 private

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def booking_params
    params.require(:booking).permit(:check_in, :check_out, :total_price)
  end
end

app/controllers/castles_controller.rb
class CastlesController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[show index]
  before_action :set_castle, only: %i[show]

  def show
    @booking = Booking.new
    @markers = [{
      lat: @castle.latitude,
      lng: @castle.longitude,
      marker_html: render_to_string(partial: "marker")
    }]
  end

  def index
    @castles = Castle.all
  end


  private

  def set_castle
    @castle = Castle.find(params[:id])
  end

  def castle_params
    params.require(:caslte).permit(:title, :description, :location, :price, :capacity, :photo, :category)
  end
end

app/controllers/owner/bookings_controller.rb
class Owner::BookingsController < ApplicationController

  def index
    @bookings = current_user.bookings_as_owner
  end

  def accept
    @booking = Booking.find(params[:id])
    @booking.update(validates: "accepted")
    redirect_to owner_bookings_path
  end

  def decline
    @booking = Booking.find(params[:id])
    @booking.update(validates: "declined")
    redirect_to owner_bookings_path
  end

  def cancel_decision
    @booking = Booking.find(params[:id])
    @booking.update(validates: "pending")
    redirect_to owner_bookings_path
  end


  private

  def booking_params
    params.require(:booking).permit(:check_in, :check_out, :total_price, :validates)
  end

end

app/controllers/owner/castles_controller.rb
class Owner::CastlesController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[show index]
  before_action :set_castle, only: %i[show]

  def new
    @castle = Castle.new
  end

  def create
    @castle = Castle.new(castle_params)
    @castle.user_id = current_user.id
    @castle.save
    redirect_to castles_path, notice: "You successfully add a castle !"
  end

  private

  def set_castle
    @castle = Castle.find(params[:id])
  end

  def castle_params
    params.require(:castle).permit(:title, :description, :location, :price, :capacity, :photo, :category)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<h1 id="bookings-h1">Your Bookings as a Renter</h1>
<div class="bookings-grid">
  <% @bookings.sort.reverse.each do |booking| %>
    <div class="bookings-card-product">
      <%= link_to castle_path(booking.castle), class: "booking-infos" do %>
        <div class="booking-img"  style="background-image: url('<%= if booking.castle.photo then cl_image_path booking.castle.photo.key end %>')">
        </div>
        <div class="booking-text">
          <h5><%= booking.castle.title %></h5>
          <h6><span class="icone-location"><i class="fa-sharp fa-solid fa-location-dot"></i></span><%= booking.castle.location %></h6>
          <p><strong>from</strong> <%= booking.check_in.strftime("%A %d %B %Y")%></p>
          <p><strong>to</strong> <%= booking.check_out.strftime("%A %d %B %Y") %></p>
          <p><strong><%= booking.total_price %> €</strong></p>
        </div>
      <% end %>
      <div class="bookings-validations">
        <div class="bookings-situation">
          <p class="confirmation-status-current"><strong>
            <% case booking.validates %>
            <% when "accepted" %>
              <%= "Booking accepted" %>
              <i class="fa-regular fa-circle-check"></i>
            <% when "declined" %>
              <%= "Booking declined" %>
              <i class="fa-regular fa-circle-xmark"></i>
            <% else %>
              <%= "Waiting for acceptation" %>
            <% end %>
          </strong></p>
        </div>
        <%=
            link_to 'Cancel my booking',
            booking_path(booking),
            data: {turbo_method: :delete, turbo_confirm: "Are you sure you want to Cancel your booking ?"},
            calss:"btn-cancel-decision",
            id:"no-decoration"
        %>
      </div>
    </div>
  <% end %>
</div>

app/views/castles/_marker.html.erb
<%= image_tag "chateau.png", class:"logochateau", alt: "Logo" %>

app/views/castles/index.html.erb
<h1 class="index-h1">
All castles
</h1>

<div class="index-cards">
  <% @castles.each do |castle| %>
    <% unless current_user == castle.user %>
      <%= link_to castle_path(castle) do %>
        <div class="index-card">
          <div>
            <div>
              <div class="index-card-image" style="background-image: url('<%= if castle.photo then cl_image_path castle.photo.key end %>')">
              </div>
              <div class="index-card-image-lineargradiant">
              </div>
            </div>
            <div class="index-card-descriptions">
              <h3><strong><%= castle.title %></strong></h3>
              <h6><span class="icone-location"><i class="fa-sharp fa-solid fa-location-dot"></i></span><%= castle.location %></h6>
              <div class="people-price">
                <h6><span class="icone-capacity"><i class="fa-sharp fa-solid fa-user-group"></i></span><%= castle.capacity %></h6>
                <h6><strong><%= castle.price %>€</strong> / night</h6>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/castles/show.html.erb
<div class="card-trip">
  <%= cl_image_tag @castle.photo.key %>
  <div class="card-trip-explications">
    <div class="card-trip-body">
      <div class="card-trip-infos">
        <div class="card-trip-infos-title">
          <h4><strong><span class="title-lign"><%= @castle.title %></span></strong></h4>
          <div class="card-trip-infos-title-category"><%= @castle.category.upcase %></div>
        </div>
        <br>
        <p class="card-trip-capacity-and-location"><i class="fa-sharp fa-solid fa-user-group"></i> <strong><%=@castle.capacity %></strong> <em>travellers</em>&ensp;•&ensp;<strong><em><%=@castle.location%></em></strong></p>
        <p class="card-trip-description"><em><%= @castle.description %></em></p>
        <br>
      </div>
      <div class="separation-lign"></div>
      <div class="card-trip-owner">
      <br>
        <h3><%= cl_image_tag @castle.user.photo.key, class:"owner-image"%> <strong><%= @castle.user.first_name %> <%= @castle.user.last_name %></strong></h3>
        <p><em><%= @castle.user.description %></em></p>
      </div>
      <div class="separation-lign"></div>
      <br>
      <div class="map-section" >
        <h3><strong> Find out where the castle is located </strong></h3>
        <br>
        <div class="display-map" data-controller="map"
          data-map-markers-value="<%= @markers.to_json %>"
          data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"></div>
      </div>
    </div>
    <div class="card-trip-form" data-controller="totalprice" data-price="<%= @castle.price %>">
        <%= simple_form_for [@castle, @booking] do |f| %>

          <h6 class="card-trip-pricing"> <strong><%= @castle.price %></strong> € per night</h6>
          <br>
          <%= f.input :check_in, html5: true, label: "CHECK-IN", input_html: {data: { totalprice_target: 'checkin', action: "input->totalprice#calculatePrice"}} %>
          <%= f.input :check_out, html5: true, label: "CHECK-OUT", input_html: {data: { totalprice_target: 'checkout', action: "totalprice#calculatePrice" }}  %>
          <%= f.submit "Reserve", class:"button-booking" %>
          <%= f.input :total_price, label: false, input_html: {class:"d-none"} %>
        <% end %>
        <br>
        <div id="bill" class="d-flex flex-column sticky-top">
          <div class="d-flex justify-content-between">
            <div>
              <h3 id="loc"> <%= @castle.price %> €</h3>
            </div>
            <div>
              <h3 id="totalloc"> € </h3>
            </div>
          </div>
          <div class="d-flex justify-content-between">
            <div>
              <h3> Cleaning fee </h3>
            </div>
            <div>
              <h3 id="clfee"> € </h3>
            </div>
          </div>
          <div class="total-line"></div>
          <div class="d-flex justify-content-between">
            <div>
              <h3> Total </h3>
            </div>
            <div>
              <h3 id="total"> € </h3>
            </div>
          </div>
        </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
  <head>
    <title>EXEPTIONS</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.js"></script>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "/assets/javascript/application", "data-turbo-track": "reload", defer: true %>

    <link rel="stylesheet" href="assets/css/style.css">
  </head>

  <body>
  <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <div class="left-navbar">
    </div>
    <%= link_to root_path  do %>
      <%# <a class="navbar-brand" href="#"> %>
        <%= image_tag "logo-navbar.png", class:"navbar-brand-img" %>
      <%# </a> %>
    <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <div class="my-boutn">
          <%= link_to 'Add an offer', new_owner_castle_path %>
        </div>
          <li class="nav-item dropdown">
            <% if user_signed_in? %>
              <% if (current_user.photo.key).nil? %>
                <%= image_tag "icon-logo-user-connected.jpg", class:"avatar dropdown-toggle", id:"navbarDropdown", data: {bs_toggle:"dropdown"},"aria-haspopup": true, "aria-expanded": false %>
              <% else %>
                <%= cl_image_tag current_user.photo.key, width: 150, height: 150, crop: :thumb, gravity: :face, class:"avatar dropdown-toggle", id:"navbarDropdown", data: {bs_toggle:"dropdown"},"aria-haspopup": true, "aria-expanded": false %>
              <% end %>
              <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="#">My Account</a>
                <%= link_to "My bookings", bookings_path, class:"dropdown-item" %>
                <%= link_to "My offers", owner_bookings_path, class:"dropdown-item" %>
                <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete }, class: "dropdown-item" %>
              </div>
            <% else %>
              <%= image_tag "icon-logo-user.png", class:"avatar dropdown-toggle", id:"navbarDropdown", data: {bs_toggle:"dropdown"},"aria-haspopup": true, "aria-expanded": false %>
              <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="/users/sign_in">Sign in</a>
              </div>
            <% end %>
          </li>
      </ul>
    </div>
  </div>
</div>
    <%= yield %>
    <%# <%= render "shared/navbar" %>
     <% flash.each do |type, msg| %>
      <div class="alert alert-info">
        <%= msg %>
      </div>
    <% end %>
    <%# <%= render "shared/flashes" %>
    <div class="footer-basic">
        <footer>
            <div class="social"><a href="#"><i class="fa-brands fa-instagram"></i></a><a href="#"><i class="fa-brands fa-facebook"></i></a><a href="#"><i class="fab fa-linkedin"></i></a></div>
            <ul class="list-inline">
                <li class="list-inline-item"><a href="#">Home</a></li>
                <li class="list-inline-item"><a href="#">Services</a></li>
                <li class="list-inline-item"><a href="#">About</a></li>
                <li class="list-inline-item"><a href="#">Terms</a></li>
                <li class="list-inline-item"><a href="#">Privacy Policy</a></li>
            </ul>
            <p class="copyright">© 2023 Exeptions</p>
        </footer>
    </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"></script>
  </body>
</html>

app/views/owner/bookings/index.html.erb
<h1 id="bookings-h1">Your Bookings as an Owner</h1>
<div class="bookings-grid">
  <% @bookings.sort.reverse.each do |booking| %>
    <div class="bookings-card-product">
      <%= link_to castle_path(booking.castle), class: "booking-infos" do %>
        <div class="booking-img"  style="background-image: url('<%= if booking.castle.photo then cl_image_path booking.castle.photo.key end %>')">
        </div>
        <div class="booking-text">
          <h5><%= booking.castle.title %></h5>
          <h6><span class="icone-location"><i class="fa-sharp fa-solid fa-location-dot"></i></span><%= booking.castle.location %></h6>
          <p><strong>from</strong> <%= booking.check_in.strftime("%A %d %B %Y")%></p>
          <p><strong>to</strong> <%= booking.check_out.strftime("%A %d %B %Y") %></p>
          <p><strong><%= booking.total_price %> €</strong></p>
        </div>
      <% end %>
      <div class="bookings-validations">
        <div class="bookings-situation" id="bookings-situation-owner">
          <div class="confirmation-status-pending">
            <% case booking.validates %>
            <% when "accepted" %>
                <p id="text"><strong>Booking accepted</strong>
                <i class="fa-regular fa-circle-check"></i></p>
                <div>
                  <%= link_to 'Cancel my decision',
                    cancel_decision_owner_booking_path(booking),
                    data: {turbo_method: :patch, turbo_confirm: "Are you sure you want to Cancel your decision?"},
                    calss:"btn-cancel-decision-owner",
                    id:"no-decoration"
                  %>
                </div>
            <% when "declined" %>
                <p id="text"><strong>Booking declined</strong>
                <i class="fa-regular fa-circle-xmark"></i></p>
                <div>
                  <%= link_to 'Cancel my decision',
                    cancel_decision_owner_booking_path(booking),
                    data: {turbo_method: :patch, turbo_confirm: "Are you sure you want to Cancel your decision?"},
                    calss:"btn-cancel-decision-owner",
                    id:"no-decoration"
                  %>
                </div>
            <% else %>
              <p id="text"><strong>Waiting for acceptation</strong></p>
            <% end%>
          </div>
        </div>
        <% if booking.validates == "pending" %>
          <div class="bookings-acceptation">
            <%= link_to 'Accept',
              accept_owner_booking_path(booking),
              data: {turbo_method: :patch, turbo_confirm: "Are you sure you want to Accept the offer?"},
              class:"btn-accept"
            %>
            <%= link_to 'Decline',
              decline_owner_booking_path(booking),
              data: {turbo_method: :patch, turbo_confirm: "Are you sure you want to Decline the offer?"},
              class:"btn-decline"
            %>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/owner/castles/_form.html.erb
  <%= simple_form_for [:owner, @castle] do |f| %>
    <%= f.input :title, placeholder: 'title', label: false, input_html: {class:"formulaire"} %>
    <%= f.input :description, placeholder: 'write a description', label: false, input_html: {class:"formulaire"} %>
    <%= f.input :location, placeholder: 'location', label: false, input_html: {class:"formulaire"} %>
    <%= f.input :category, placeholder:'category', collection:['Countryside','Sea and beach'], label: false, prompt:"chose a category", input_html: {class:"formulaire-vol-2"} %>
    <%= f.input :price, placeholder: 'price', label: false, input_html: {class:"formulaire"} %>
    <%= f.input :capacity, placeholder: 'capacity', label: false, input_html: {class:"formulaire"} %>
    <%= f.input :photo, as: :file, label: false, input_html: {class:"formulaire"} %>
    <%= f.submit class:"button-28"%>
  <% end %>

  <%# sweet-alerts %>

app/views/owner/castles/new.html.erb
<div class="container mt-4">
  <div class="row">
    <div class="col-6 m-auto">
      <div class="castle-form">
        <h1 class="title-owner-castle">Add your Castle</h1>
          <%= render "form", castle: @castle %>
      </div>
        <div class= "mb-5">
        </div>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="home-page-image-text">
  <div class="container banner-container">
    <h3 class="text-principal">Unique castles to rent in France</h3>
    <br>
    <div class="home-page-text">
      Experience a castle with fascinating history, throughout France
    </div>
    <strong><%=link_to "Discover", castles_path, class:"my-new-button", id:"button-white-homepage" %></strong>
  </div>
</div>